Repository ls1intum/Athena, pull requests merged in 2023-07, with the labels that each got.

#56 Improve feedback and some fixes
  athena/athena/endpoints.py
  athena/athena/models/db_feedback.py
  athena/athena/schemas/feedback.py
  athena/athena/schemas/programming_feedback.py
  athena/athena/storage/feedback_storage.py
  module_example/module_example/__main__.py
  module_programming_llm/module_programming_llm/basic/basic_feedback_provider.py
  module_text_llm/module_text_llm/suggest_feedback_basic.py
  playground/data/example/exercise-1.json
  playground/data/example/exercise-1/submissions/101/BinarySearch.java
  playground/data/example/exercise-2.json
  playground/data/example/exercise-3.json
  playground/scripts/artemis/export_programming_exercises.sql
  playground/scripts/artemis/export_text_exercises.sql
  playground/src/components/base_info_header.tsx
  playground/src/components/details/exercise_detail/common.tsx
  playground/src/components/details/exercise_detail/index.tsx
  playground/src/components/details/exercise_detail/programming.tsx
  playground/src/components/details/exercise_detail/text.tsx
  playground/src/components/details/feedback.tsx
  playground/src/components/details/submission_detail/index.tsx
  playground/src/components/details/submission_detail/programming.tsx
  playground/src/components/details/submission_detail/text.tsx
  playground/src/components/health.tsx
  playground/src/components/module_config/index.tsx
  playground/src/components/module_requests/get_config_schema.tsx
  playground/src/components/module_requests/index.tsx
  playground/src/components/module_requests/request_feedback_suggestions.tsx
  playground/src/components/module_requests/request_submission_selection.tsx
  playground/src/components/module_requests/send_feedback.tsx
  playground/src/components/module_requests/send_submissions.tsx
  playground/src/components/module_response_view.tsx
  playground/src/components/selectors/data_select.tsx
  playground/src/components/selectors/exercise_select.tsx
  playground/src/components/selectors/feedback_select.tsx
  playground/src/components/selectors/module_select.tsx
  playground/src/components/selectors/submission_select.tsx
  playground/src/components/submission_list.tsx
  playground/src/helpers/client/get_data.ts
  playground/src/helpers/get_data.ts
  playground/src/helpers/origin_from_req.ts
  playground/src/helpers/validate_mode_middleware.ts
  playground/src/model/feedback.ts
  playground/src/model/health_response.ts
  playground/src/model/module_response.ts
  playground/src/pages/api/health.ts
  playground/src/pages/api/mode/[mode]/exercise/[exerciseId]/data/[...path].ts
  playground/src/pages/api/mode/[mode]/exercise/[exerciseId]/feedbacks.ts
  playground/src/pages/api/mode/[mode]/exercise/[exerciseId]/submissions.ts
  playground/src/pages/api/mode/[mode]/exercises.ts
  playground/src/pages/api/mode/[mode]/feedbacks.ts
  playground/src/pages/api/mode/[mode]/submissions.ts
  playground/src/pages/index.tsx
Labels: bug, enhancement

#52 Improve playground requests and state management
  playground/package-lock.json
  playground/package.json
  playground/src/components/base_info_header.tsx
  playground/src/components/details/code_view/index.tsx
  playground/src/components/details/exercise_detail/common.tsx
  playground/src/components/details/exercise_detail/index.tsx
  playground/src/components/details/exercise_detail/programming.tsx
  playground/src/components/details/exercise_detail/text.tsx
  playground/src/components/details/feedback.tsx
  playground/src/components/form/description_field.tsx
  playground/src/components/health.tsx
  playground/src/components/module_config/index.tsx
  playground/src/components/module_requests/get_config_schema.tsx
  playground/src/components/module_requests/index.tsx
  playground/src/components/module_requests/request_feedback_suggestions.tsx
  playground/src/components/module_requests/request_submission_selection.tsx
  playground/src/components/module_requests/send_feedback.tsx
  playground/src/components/module_requests/send_submissions.tsx
  playground/src/components/module_response_view.tsx
  playground/src/components/selectors/exercise_select.tsx
  playground/src/components/selectors/feedback_select.tsx
  playground/src/components/selectors/module_select.tsx
  playground/src/components/selectors/submission_select.tsx
  playground/src/components/submission_list.tsx
  playground/src/helpers/client/get_data.ts
  playground/src/helpers/fetcher.ts
  playground/src/helpers/get_data.ts
  playground/src/hooks/athena/config_schema.ts
  playground/src/hooks/athena/request_feedback_suggestions.ts
  playground/src/hooks/athena/request_submission_selection.ts
  playground/src/hooks/athena/send_feedback.ts
  playground/src/hooks/athena/send_submissions.ts
  playground/src/hooks/athena_fetcher.ts
  playground/src/hooks/base_info_context.tsx
  playground/src/hooks/health.ts
  playground/src/hooks/playground/exercises.ts
  playground/src/hooks/playground/feedbacks.ts
  playground/src/hooks/playground/submissions.ts
  playground/src/model/module_response.ts
  playground/src/pages/_app.tsx
  playground/src/pages/index.tsx
Labels: enhancement

#57 Update all dependencies
  assessment_module_manager/poetry.lock
  athena/poetry.lock
  module_example/poetry.lock
  module_programming_llm/poetry.lock
  module_programming_llm/pyproject.toml
  module_programming_themisml/poetry.lock
  module_text_cofee/poetry.lock
  module_text_llm/poetry.lock
  playground/package-lock.json
  playground/package.json
  poetry.lock
Labels: python, playground

#62 Fix config schema detection error on production setups
  athena/athena/endpoints.py
  athena/poetry.lock
  athena/pyproject.toml
  module_example/poetry.lock
  module_programming_llm/poetry.lock
  module_programming_themisml/poetry.lock
  module_text_cofee/poetry.lock
  module_text_llm/poetry.lock
Labels: python

#66 Quick fix: Add ThemisML secret env variable for assessment module manager
  env_example/assessment_module_manager.env
Labels: bug
