Repository ls1intum/Athena, pull requests merged in 2023-12, with the labels that each got.

#187 `CoFee`: Prefix CoFee database table names
  module_text_cofee/module_text_cofee/models/db_text_block.py
  module_text_cofee/module_text_cofee/models/db_text_cluster.py
Labels: python

#184 `Documentation`: Add Athena overview
  docs/_static/css/style.css
  docs/images/subsystem_decomposition.svg
  docs/index.rst
  docs/overview/athena.rst
Labels: documentation

#195 Add timestamps to logging messages
  assessment_module_manager/assessment_module_manager/__main__.py
  assessment_module_manager/assessment_module_manager/app.py
  assessment_module_manager/assessment_module_manager/env.py
  assessment_module_manager/assessment_module_manager/logger.py
  athena/athena/app.py
  athena/athena/logger.py
  module_programming_themisml/module_programming_themisml/__main__.py
Labels: lock:athena-test3
