Repository ls1intum/Athena, pull requests merged in 2023-10, with the labels that each got.

#79 Use OpenAI function calling and general improvements for `module_text_llm`
  module_text_llm/.env.example
  module_text_llm/module_text_llm/__main__.py
  module_text_llm/module_text_llm/config.py
  module_text_llm/module_text_llm/generate_suggestions.py
  module_text_llm/module_text_llm/helpers/llm_utils.py
  module_text_llm/module_text_llm/helpers/models/openai.py
  module_text_llm/module_text_llm/helpers/models/replicate.py
  module_text_llm/module_text_llm/helpers/utils.py
  module_text_llm/module_text_llm/prompts/generate_suggestions.py
  module_text_llm/module_text_llm/suggest_feedback_basic.py
  module_text_llm/poetry.lock
  module_text_llm/pyproject.toml
Labels: enhancement, dependencies, python

#83 General improvements for `module_programming_llm`
  athena/athena/helpers/programming/code_repository.py
  athena/athena/schemas/programming_exercise.py
  env_example/module_programming_llm.env
  module_programming_llm/.env.example
  module_programming_llm/module_programming_llm/__main__.py
  module_programming_llm/module_programming_llm/basic/basic_feedback_provider.py
  module_programming_llm/module_programming_llm/basic/file_instructions.py
  module_programming_llm/module_programming_llm/basic/prompts/basic_feedback_provider.py
  module_programming_llm/module_programming_llm/basic/prompts/generate_file_grading_instructions.py
  module_programming_llm/module_programming_llm/basic/prompts/generate_file_problem_statements.py
  module_programming_llm/module_programming_llm/config.py
  module_programming_llm/module_programming_llm/generate_suggestions_by_file.py
  module_programming_llm/module_programming_llm/helpers/llm_utils.py
  module_programming_llm/module_programming_llm/helpers/models.py
  module_programming_llm/module_programming_llm/helpers/models/__init__.py
  module_programming_llm/module_programming_llm/helpers/models/model_config.py
  module_programming_llm/module_programming_llm/helpers/models/openai.py
  module_programming_llm/module_programming_llm/helpers/models/replicate.py
  module_programming_llm/module_programming_llm/helpers/utils.py
  module_programming_llm/module_programming_llm/prompts/generate_suggestions_by_file.py
  module_programming_llm/module_programming_llm/prompts/split_grading_instructions_by_file.py
  module_programming_llm/module_programming_llm/prompts/split_problem_statement_by_file.py
  module_programming_llm/module_programming_llm/split_grading_instructions_by_file.py
  module_programming_llm/module_programming_llm/split_problem_statement_by_file.py
  module_programming_llm/poetry.lock
  module_programming_llm/pyproject.toml
  playground/src/components/selectors/module_config_select/index.tsx
Labels: enhancement, dependencies, python

#145 Update dependencies
  module_programming_llm/poetry.lock
  module_programming_llm/pyproject.toml
  module_text_llm/poetry.lock
  module_text_llm/pyproject.toml
Labels: dependencies

#147 Update root poetry lock file
  poetry.lock
Labels: dependencies

#149 Update playground dependencies and remove unnecessary dependencies
  playground/package-lock.json
  playground/package.json
Labels: lock:athena-test3, playground

#153 ThemisML Python upgrade
  module_programming_themisml/Dockerfile
  module_programming_themisml/poetry.lock
  module_programming_themisml/pyproject.toml
Labels: lock:athena-test3

#164 Fix Git commit error with missing email and name
  athena/athena/helpers/programming/code_repository.py
Labels: lock:athena-test3

#160 Add experiment middleware and LLM call tags for logging
  assessment_module_manager/assessment_module_manager/endpoints/modules_proxy_endpoint.py
  assessment_module_manager/assessment_module_manager/module/request_to_module.py
  athena/athena/__init__.py
  athena/athena/app.py
  athena/athena/experiment.py
  module_programming_llm/module_programming_llm/generate_suggestions_by_file.py
  module_programming_llm/module_programming_llm/helpers/llm_utils.py
  module_programming_llm/module_programming_llm/split_grading_instructions_by_file.py
  module_programming_llm/module_programming_llm/split_problem_statement_by_file.py
  module_text_llm/module_text_llm/generate_suggestions.py
  module_text_llm/module_text_llm/helpers/llm_utils.py
  playground/src/components/view_mode/evaluation_mode/conduct_experiment/batch_module_experiment.tsx
  playground/src/hooks/athena_fetcher.ts
  playground/src/hooks/experiment_identifiers_context.tsx
Labels: lock:athena-test3

#166 Fix send training feedback getting stuck
  playground/src/hooks/batch_module_experiment.ts
Labels: lock:athena-test3

#161 Update langchain
  module_programming_llm/poetry.lock
  module_programming_llm/pyproject.toml
  module_text_llm/poetry.lock
  module_text_llm/pyproject.toml
Labels: dependencies

#162 Display structured grading instructions in Playground
  playground/src/components/details/editor/inline_feedback.tsx
  playground/src/components/details/exercise_detail/common.tsx
  playground/src/components/details/exercise_detail/structured_grading_instruction_detail.tsx
  playground/src/components/details/feedback.tsx
  playground/src/components/markdown.tsx
  playground/src/model/exercise.ts
Labels: playground

#163 Add grading criteria support for llm modules
  athena/athena/__init__.py
  athena/athena/schemas/__init__.py
  athena/athena/schemas/feedback.py
  module_programming_llm/module_programming_llm/generate_suggestions_by_file.py
  module_programming_llm/module_programming_llm/helpers/utils.py
  module_programming_llm/module_programming_llm/split_grading_instructions_by_file.py
  module_text_llm/module_text_llm/generate_suggestions.py
  module_text_llm/module_text_llm/helpers/utils.py
Labels: enhancement, python
