Repository ls1intum/Athena, pull requests merged in 2024-08, with the labels that each got.

#323 `Module_text_llm`: Upgrade dependencies and openai model retrieval
  module_text_llm/.env.example
  module_text_llm/module_text_llm/helpers/models/__init__.py
  module_text_llm/module_text_llm/helpers/models/openai.py
  module_text_llm/module_text_llm/helpers/models/replicate.py
  module_text_llm/poetry.lock
  module_text_llm/pyproject.toml
Labels: lock:athena-test1

#327 Fix OpenAI model configuration
  module_text_llm/.env.example
  module_text_llm/module_text_llm/helpers/models/openai.py
Labels: enhancement, lock:athena-test1, python

#326 `module_modeling_LLM`: Fix the handling of BPMN diagrams without pools
  module_modeling_llm/module_modeling_llm/helpers/serializers/bpmn_serializer.py
Labels: lock:athena-test1

#332 `Development`: Simplify AMM Dockerfile and add modules config to docker compose prod
  assessment_module_manager/Dockerfile
  docker-compose.prod.yml
Labels: lock:athena-test2

#330 `Playground`: UI Improvements to inline feedback
  playground/src/components/details/editor/inline_feedback.tsx
  playground/src/hooks/playground/feedbacks.ts
  playground/src/model/feedback.ts
Labels: ready to review
